import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { excercises } from "../src/lib/excercises.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(__dirname, "../src/lib/video-thumbnails.ts");

async function fetchThumbnail(videoUrl: string): Promise<string> {
  const res = await fetch(
    `https://vimeo.com/api/oembed.json?url=${encodeURIComponent(videoUrl)}&width=640`
  );
  if (!res.ok) {
    throw new Error(`${videoUrl}: HTTP ${res.status}`);
  }
  const data = (await res.json()) as { thumbnail_url: string };
  return data.thumbnail_url;
}

function collectVideoUrls(): string[] {
  const urls = new Set<string>();
  for (const exercise of excercises) {
    for (const progression of exercise.progression) {
      if (progression.videoUrl) {
        urls.add(progression.videoUrl);
      }
    }
  }
  return [...urls].sort();
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const urls = collectVideoUrls();
  console.log(`Fetching thumbnails for ${urls.length} videos…`);

  const thumbnails: Record<string, string> = {};
  const failures: string[] = [];

  for (const url of urls) {
    try {
      thumbnails[url] = await fetchThumbnail(url);
      console.log(`✓ ${url}`);
    } catch (err) {
      failures.push(url);
      console.error(`✗ ${url}:`, err instanceof Error ? err.message : err);
    }
    await sleep(200);
  }

  if (failures.length > 0) {
    console.error(`\n${failures.length} failed — output not written.`);
    process.exit(1);
  }

  const entries = Object.entries(thumbnails)
    .map(([url, thumb]) => `  ${JSON.stringify(url)}: ${JSON.stringify(thumb)},`)
    .join("\n");

  const content = `// Generated by scripts/fetch-thumbnails.ts — do not edit manually.
// Re-run: npm run fetch-thumbnails

export const VIDEO_THUMBNAILS: Record<string, string> = {
${entries}
};
`;

  writeFileSync(OUTPUT, content);
  console.log(`\nWrote ${OUTPUT}`);
}

main();
